{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<img src={"collaboration/approvelocation.png"|ezimage} alt="{'Location approval'|i18n('design/standard/collaboration')}" width="16" height="16" />
