{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<form method="post" action={"collaboration/action/"|ezurl}>
{let message_limit=2
     message_offset=0
     content_version=fetch("content","object",hash("object_id",$collab_item.content.content_object_id,"version_id",$collab_item.content.content_object_version))
     current_participant=fetch("collaboration","participant",hash("item_id",$collab_item.id))
     participant_list=fetch("collaboration","participant_map",hash("item_id",$collab_item.id))
     message_list=fetch("collaboration","message_list",hash("item_id",$collab_item.id,"limit",$message_limit,"offset",$message_offset))
}
{* Recover from target node ids, the full content nodes *}
{def $target_nodes = array()}
{if and( is_set($collab_item.content.target_node_ids), $collab_item.content.target_node_ids|count()|gt(0) ) }
	{foreach $collab_item.content.target_node_ids as $target_node_id}
		{set $target_nodes = $target_nodes|append(fetch('content', 'node', hash('node_id', $target_node_id ) ) ) }
	{/foreach}
{/if}
{if $content_version|null()|not()}
  {set-block variable=contentobject_link}
    {node_view_gui view=text_linked content_node=$content_version.main_node}
  {/set-block}
{/if}

{set-block variable=target_node_links}
{if $target_nodes|count()|gt(0)}
	{foreach $target_nodes as $target_node}
	    {node_view_gui view=text_linked content_node=$target_node}
	    {delimiter}, {/delimiter}
	{/foreach}
{/if}
{/set-block}
<table cellspacing="4" cellpadding="4" border="0">
<tr>
  <td rowspan="2" valign="top">

<div class="objectheader">
<h2>{"Location approval"|i18n('design/standard/collaboration/approval')}</h2>
</div>

<div class="object">

{switch match=$collab_item.data_int3}
{case match=0}

{if $collab_item.is_creator}
<p>{"The content object %1 awaits approval before the following location(s):"|i18n('design/standard/collaboration/approval',,array($contentobject_link) ) } {$target_node_links}</p>
<p>{"Do you want to send a message to the person approving it?"|i18n('design/standard/collaboration/approval')}</p>
{else}
<p>{"The content object %1 needs your approval."|i18n('design/standard/collaboration/approval',,array($contentobject_link))}</p>
<p>{"Do you approve the content object %1 to be located in the following location(s)?"|i18n('design/standard/collaboration/approval', , array($contentobject_link) ) } {$target_node_links}</p>
{/if}

{/case}
{case match=1}
  <p>{"The content object %1 new location(s) %2 was approved."|i18n('design/standard/collaboration/approval',,array($contentobject_link, $target_node_links))}</p>
{/case}
{case in=array(2,3)}
  {if $collab_item.is_creator}
    <p>{"The content object %1 new location(s) %2 was not accepted."|i18n('design/standard/collaboration/approval',,array($contentobject_link, $target_node_links))}</p>
    {if $content_version|null()|not()}
      <p>{"You can add a new location, in which case an approval will be required again."|i18n('design/standard/collaboration/approval')}</p>
      <p>{"View the content"|i18n('design/standard/collaboration/approval')} {$contentobject_link}</p>
    {/if}
  {else}
    <p>{"The content object %1 new location(s) %2 was not accepted."|i18n('design/standard/collaboration/approval',,array($contentobject_link, $target_node_links ))}</p>
    <p>{"The author can add a new location, in which case a new approval will be required again."|i18n('design/standard/collaboration/approval')}</p>
  {/if}
{/case}
{case/}
{/switch}

<input type="hidden" name="CollaborationActionCustom" value="custom" />
<input type="hidden" name="CollaborationTypeIdentifier" value="approvelocation" />

<input type="hidden" name="CollaborationItemID" value="{$collab_item.id}" />

<br/>

{if eq($collab_item.data_int3,0)}
<label>{"Comment"|i18n('design/standard/collaboration/approval')}</label><div class="break"/>
<textarea name="Collaboration_ApproveLocationComment" cols="40" rows="5"></textarea>

<div class="buttonblock">
<input type="submit" name="CollaborationAction_Comment" value="{'Add Comment'|i18n('design/standard/collaboration/approval')}" />

&nbsp;

{if $collab_item.is_creator|not}
<input type="submit" name="CollaborationAction_Accept" value="{'Approve'|i18n('design/standard/collaboration/approval')}" />
<input type="submit" name="CollaborationAction_Deny" value="{'Deny'|i18n('design/standard/collaboration/approval')}" />
{/if}
</div>
{/if}

</div>

  </td>

  <td rowspan="2" valign="top">

{if $content_version|null()|not()}
	{node_view_gui view=plain content_node=$content_version.main_node}
{/if}

  </td>

  <td rowspan="2" valign="top">

<div class="objectheader">
   <h2>{"Participants"|i18n('design/standard/collaboration/approval')}</h2>
</div>

<div class="object">
   {section name=Role loop=$participant_list}
   <label>{$:item.name|wash}</label>
   <table cellspacing="0" cellpadding="0" border="0">
   {section name=Participant loop=$:item.items}
   <tr>
     <td>
     {collaboration_participation_view view=text_linked collaboration_participant=$:item}
     </td>
   </tr>
   {/section}
   </table>
   {delimiter}<br/>{/delimiter}
   {/section}
</div>

  </td>

</tr>
</table>

{section show=$message_list}

  <h1 id="messages">{"Messages"|i18n('design/standard/collaboration/approval')}</h1>
  <table width="100%" cellspacing="0" cellpadding="4" border="0">
  {section name=Message loop=$message_list sequence=array(bglight,bgdark)}

      {collaboration_simple_message_view view=element sequence=$:sequence is_read=$current_participant.last_read|gt($:item.modified) item_link=$:item collaboration_message=$:item.simple_message}

  {/section}
  </table>

{/section}

{/let}

</form>
